//
// Copyright Jason Rice 2026
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
#ifndef NBDL_MEMREF_HPP
#define NBDL_MEMREF_HPP

#include <array>
#include <cstddef>
#include <cstdint>
#include <tuple>
#include <type_traits>

namespace nbdl {
  // Represent a view of a contiguous block of memory for
  // use with binding MLIR memrefs. Guarantee, only, that
  // the object can be destructured to the same elements,
  // strictly ordered, such that it can be passed to a
  // function whose prototype was generated by lowering a
  // FuncOp taking a memref argument.
  template <typename T,
            std::size_t Rank = 1,
            typename IndexType = std::intptr_t>
  struct memref {
    using value_type = T;
    using index_type = IndexType;
    static constexpr std::size_t rank = Rank;

    T* allocated;
    T* aligned;
    IndexType offset;
    std::array<IndexType, Rank> sizes;
    std::array<IndexType, Rank> strides;

    template <std::size_t I>
    constexpr auto get() const {
      if constexpr (I == 0) {
        return allocated;
      }
      else if constexpr (I == 1) {
        return aligned;
      }
      else if constexpr (I == 2) {
        return offset;
      }
      else if constexpr (I < 3 + Rank) {
        return sizes[I - 3];
      }
      else {
        static_assert(I < 3 + 2 * Rank, "index out of range");
        return strides[I - 3 - Rank];
      }
    }
  };

  template <typename T, typename IndexType>
  struct memref<T, 1, IndexType> {
    using value_type = T;
    using index_type = IndexType;
    static constexpr std::size_t rank = 1;

    T* allocated;
    T* aligned;
    IndexType offset;
    IndexType size;
    IndexType stride;
  };
}

namespace std {
  // Excludes Rank == 1: that specialization is a flat aggregate destructured
  // via the "public data members" structured-binding rule, not this
  // tuple-like protocol -- see nbdl/memref.hpp.
  template <typename T, std::size_t Rank, typename IndexType>
    requires (Rank != 1)
  struct tuple_size<nbdl::memref<T, Rank, IndexType>>
    : std::integral_constant<std::size_t, 3 + 2 * Rank> { };

  template <std::size_t I, typename T, std::size_t Rank, typename IndexType>
    requires (Rank != 1)
  struct tuple_element<I, nbdl::memref<T, Rank, IndexType>> {
    using type = std::conditional_t<(I < 2), T*, IndexType>;
  };
}

#endif
