//
// Copyright Jason Rice 2025
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
#ifndef NBDL_SPEC_HPP
#define NBDL_SPEC_HPP

// FIXME nbdl::assign probably does not need its own file.
#include <nbdl/assign.hpp>
#include <nbdl/concept/extras.hpp>
#include <nbdl/ext/std/tuple_like.hpp>
#include <nbdl/get.hpp>
#include <nbdl/match.hpp>
#include <nbdl/store_compose.hpp>
#include <nbdl/strong_alias.hpp>
#include <nbdl/tags.hpp>
#include <nbdl/variant.hpp>
#include <nbdl/variant_holder.hpp>
#include <boost/hana/functional/overload.hpp>
#include <algorithm>
#include <concepts>
#include <type_traits>
#include <utility>

// Include and define functions and hooks
// required for code generated by the
// (nbdl spec) Scheme DSL.

namespace nbdl::detail {
template <int>
struct probe {
  template <typename ...>
  struct apply { };
};

// Implement our own declval to use in an evaluated context.
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type"
template <typename T>
T&& declval() { }
#pragma clang diagnostic pop
#else
template <typename T>
T&& declval();
#endif // defined(__clang__)

struct invalid { }; // Tag for sfinae_result

template <typename Result>
struct sfinae_result {
  Result sfinae_result_value;

  constexpr explicit operator bool() const {
    if constexpr (requires { static_cast<bool>(sfinae_result_value); })
      return sfinae_result_value;
    else
      return true;
  }
};

template <>
struct sfinae_result<invalid> {
  constexpr explicit operator bool() const {
    return false;
  }
};

template <>
struct sfinae_result<void> {
  constexpr explicit operator bool() const {
    return true;
  }
};

template <typename ThunkFn>
struct sfinae {
  ThunkFn fn;

  // Note `sfinae_result` is aggregate initialized
  // to prevent a dangling reference.
  template <typename ...Args>
  decltype(auto) operator()(Args&& ...args) const {
    if constexpr(std::invocable<ThunkFn, Args...>) {
      if constexpr(std::same_as<std::invoke_result_t<ThunkFn, Args...>, void>)
        return sfinae_result<void>{};
      else
        return sfinae_result{std::invoke(fn, std::forward<Args>(args)...)};
    } else {
      return sfinae_result<invalid>{};
    }
  }
};
} // namespace nbdl::detail

namespace nbdl {
  // TODO Implement match_impl.
//template <typename ThunkFn>
} // namespace nbdl


#endif // NBDL_SPEC_HPP
