; RUN: heavy-scheme %s | FileCheck %s
(import (heavy base))

; CHECK: (1 2 "yo")
; COM:CHECK: (1 2 . "yo")
(write (list 1 2 "yo"))(newline)

(define nums (list 1 2 3))
; CHECK: (1 2 3)
(write nums)(newline)
; CHECK-NEXT: (0 1 2 3)
(write (cons 0 nums))(newline)
; CHECK-NEXT: (1 2 3)
(write nums)(newline)
; CHECK-NEXT: 1
(write (car nums))(newline)
; CHECK-NEXT: (2 3)
(write (cdr nums))(newline)
; CHECK-NEXT: (1 2 3)
(write (append nums))(newline)
; CHECK-NEXT: (1 2 3)
(write (append nums '()))(newline)
; CHECK-NEXT: (1 2 3)
(write (append '() nums))(newline)
; CHECK-NEXT: (4 5 6 1 2 3)
(write (append '(4 5 6) nums))(newline)
; CHECK-NEXT: (1 2 3 4 5 6)
(write (append nums '(4 5 6)))(newline)
; CHECK-NEXT: (0 1 2 3 4 5 6)
(write (append '(0) nums '(4 5 6)))(newline)
; CHECK-NEXT: (0 1 2 3 4 5 6 1 2 3)
(write (append '(0) nums '(4 5 6) nums))(newline)
; CHECK-NEXT: (1 2 3)
(write nums)(newline)
