; RUN: heavy-scheme %s | FileCheck %s
(import (heavy builtins))

; CHECK: (#t #f #f)
(write `(,(boolean? #t)
         ,(boolean? 5)
         ,(boolean? #\a)))
(newline)

; CHECK-NEXT: (#t #t #f #f)
(write `(,(char? #\a)
         ,(char? #\space)
         ,(char? #t)
         ,(char? 5)))
(newline)

; CHECK-NEXT: (#t #f #f)
(write `(,(number? 5)
         ,(number? #t)
         ,(number? #\a)))
(newline)

; CHECK-NEXT: (#t #f #f)
(write `(,(null? '())
         ,(null? '(1))
         ,(null? 0)))
(newline)

; CHECK-NEXT: (#t #t #t #f #f)
(write `(,(pair? '(5))
         ,(pair? '(1 2))
         ,(pair? '(1 . 2))
         ,(pair? '())
         ,(pair? 0)))
(newline)

; CHECK-NEXT: (#t #t #t #f #f #f)
(write `(,(vector? #())
         ,(vector? #(0))
         ,(vector? #(1 2 "moo"))
         ,(vector? '(1 . 2))
         ,(vector? '())
         ,(vector? 0)))
(newline)

; CHECK-NEXT: (#t #t #t #f #f #f)
(define (six-fn) 6)
(define (id-fn x) x)
(write `(,(procedure? (lambda () 5))
         ,(procedure? six-fn)
         ,(procedure? id-fn)
         ,(procedure? #(0))
         ,(procedure? '())
         ,(procedure? 0)))
(newline)
