; RUN: schir-scheme --module-path=%schir_module_path %s | FileCheck %s
(import (schir base))

; CHECK: (#t #t #t #t #t #f #f #f #f)
(write (list (number? 5)
             (number? -3)
             (number? 0)
             (number? 3.14)
             (number? -2.5)
             (number? "5")
             (number? 'five)
             (number? #\5)
             (number? ())))
(newline)

; CHECK-NEXT: (#t #t #t #t #f #f #f #f #f #f #f)
(write (list (exact-integer? 5)
             (exact-integer? -3)
             (exact-integer? 0)
             (exact-integer? (+ 1 2))
             (exact-integer? 3.14)
             (exact-integer? -2.5)
             (exact-integer? (+ 1 2.5))
             (exact-integer? "5")
             (exact-integer? 'five)
             (exact-integer? #\5)
             (exact-integer? ())))
(newline)

; CHECK-NEXT: (#t #t #t #t #f #f #f #f #f #f #f)
(write (list (flonum? 3.14)
             (flonum? -2.5)
             (flonum? (+ 1 2.5))
             (flonum? (* 2 1.5))
             (flonum? 5)
             (flonum? -3)
             (flonum? (+ 1 2))
             (flonum? "3.14")
             (flonum? 'pi)
             (flonum? #\3)
             (flonum? ())))
(newline)

; // Integral flonums are distinct from exact integers.
; CHECK-NEXT: (#t #f #t #f #t #f)
(write (list (exact-integer? 1)
             (exact-integer? 1.0)
             (flonum? 1.0)
             (flonum? 1)
             (flonum? -2.0)
             (exact-integer? -2.0)))
(newline)

; CHECK-NEXT: (1 1.0 -2.0 0.0 1000.0 3.0)
(write (list 1 1.0 -2.0 0.0 1e3 (+ 1 2.0)))
(newline)

; CHECK-NEXT: ("1" "1.0")
(write (list (number->string 1) (number->string 1.0)))
(newline)
