//===--- OpEval.cpp - Classes tree evaluation MLIR Operations ----*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
//  This file defines heavy::OpEval for tree evaluation of ops generated by OpGen
//
//===----------------------------------------------------------------------===//

#include "heavy/Builtins.h"
#include "heavy/Context.h"
#include "heavy/Mangle.h"
#include "heavy/OpGen.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/Support/Casting.h"
#include <stack>

namespace heavy {

class OpEvalImpl {
  using BlockItrTy = mlir::Block::iterator;
  using ValueMapTy = llvm::ScopedHashTable<mlir::Value, heavy::Value>;
  using ValueMapScope = typename ValueMapTy::ScopeTy;

  heavy::Context& Context;
  ValueMapTy ValueMap;
  std::stack<ValueMapScope> ValueMapScopes;

  void setValue(mlir::Value M, heavy::Value H) {
    assert(M && "must be set to a valid value");
    assert(H && "must be set to a valid value");
    ValueMap.insert(M, H);
  }

  heavy::Value getBindingOrValue(mlir::Value M) {
    assert(M && "lookup requires a valid value");
    heavy::Value V = ValueMap.lookup(M);
    if (!V && (M.getDefiningOp<UndefinedOp>() ||
               M.getDefiningOp<SetOp>())) {
      return Context.CreateUndefined();
    }

    if (!V) {
      if (GlobalOp G = M.getDefiningOp<GlobalOp>()) {
        if (G.isExternal()) {
          heavy::Value Val = Context.GetKnownValue(G.getSymName());
          setValue(M, Val);
          return Val;
        }
      }
    }

    // failure here could mean failure to capture in a closure
    assert(V && "getValue requires a value in the table");

    return V;
  }

  heavy::Value getValue(mlir::Value M) {
    heavy::Value V = getBindingOrValue(M);
    if (Binding* B = dyn_cast<Binding>(V)) {
      V = B->getValue();
    }
    return V;
  }

  static heavy::SourceLocation getSourceLocation(mlir::Location Loc) {
    return heavy::SourceLocation(mlir::OpaqueLoc
      ::getUnderlyingLocationOrNull<heavy::SourceLocationEncoding*>(Loc));
  }

public:
  OpEvalImpl(heavy::Context& C)
    : Context(C),
      ValueMap(),
      ValueMapScopes()
  {
    // there has to be at least one scope on the stack
    ValueMapScopes.emplace(ValueMap);
  }

  // Prevent copy/move since we capture this in a few lambdas.
  OpEvalImpl(OpEvalImpl const&) = delete;

  ~OpEvalImpl() {
    // Pop the scopes in order.
    while (!ValueMapScopes.empty())
      ValueMapScopes.pop();
  }

  void Eval(mlir::Operation* Op) {
    if (isa<GlobalOp, CommandOp, LoadModuleOp>(Op)) {
      Visit(Op);
      // "Calling the continuation" is handled during visitation.
    } else if (auto ModuleOp = dyn_cast<mlir::ModuleOp>(Op)) {
      auto& Ops = ModuleOp.getBody()->getOperations();
      // op_eval each top level operation.
      // Push the top level ops in reverse order
      for (auto i = Ops.rbegin(); i != Ops.rend(); ++i) {
        mlir::Operation* TL = &*i;
        auto G = dyn_cast<GlobalOp>(TL);
        // External GlobalOps are skipped.
        if ((G && !G.isExternal()) || isa<CommandOp>(TL)) {
          Context.PushCont([](heavy::Context& C, ValueRefs) mutable {
            heavy::Value Op = C.getCapture(0);
            Value Args[] = {Op};
            C.Apply(HEAVY_BASE_VAR(op_eval), Args);
          }, CaptureList{TL});
        }
      }
      return Context.Cont();
    } else {
      SetError(SourceLocation(), "op_eval expects a top level op");
    }
  }

private:
  void push_scope() {
    ValueMapScopes.emplace(ValueMap);
  }

  void pop_scope() {
    ValueMapScopes.pop();
    assert(ValueMapScopes.size() > 0 &&
        "scope stack must be balanced");
  }

  BlockItrTy next(mlir::Operation* Op) {
    return ++BlockItrTy(Op);
  }

  template <typename Message, typename Irritants>
  BlockItrTy RaiseError(Message M, Irritants Irrs) {
    Context.RaiseError(M, Irrs);

    return BlockItrTy();
  }

  template <typename StringTy>
  BlockItrTy SetError(SourceLocation Loc, StringTy Str,
                      heavy::Value Irr = heavy::Undefined()) {
    Context.setLoc(Loc);
    Context.RaiseError(Str, Irr);

    return BlockItrTy();
  }

  BlockItrTy Visit(mlir::Operation* Op) {
         if (isa<BindingOp>(Op))      return Visit(cast<BindingOp>(Op));
    else if (isa<LiteralOp>(Op))      return Visit(cast<LiteralOp>(Op));
    else if (isa<ApplyOp>(Op))        return Visit(cast<ApplyOp>(Op));
    else if (isa<ContOp>(Op))         return Visit(cast<ContOp>(Op));
    else if (isa<GlobalOp>(Op))       return Visit(cast<GlobalOp>(Op));
    else if (isa<LoadRefOp>(Op))      return Visit(cast<LoadRefOp>(Op));
    else if (isa<LoadGlobalOp>(Op))   return Visit(cast<LoadGlobalOp>(Op));
    else if (isa<LambdaOp>(Op))       return Visit(cast<LambdaOp>(Op));
    else if (isa<IfContOp>(Op))       return Visit(cast<IfContOp>(Op));
    else if (isa<ConsOp>(Op))         return Visit(cast<ConsOp>(Op));
    else if (isa<SpliceOp>(Op))       return Visit(cast<SpliceOp>(Op));
    else if (isa<SetOp>(Op))          return Visit(cast<SetOp>(Op));
    else if (isa<CommandOp>(Op))      return Visit(cast<CommandOp>(Op));
    else if (isa<PushContOp>(Op))     return Visit(cast<PushContOp>(Op));
    else if (isa<OpGenOp>(Op))        return Visit(cast<OpGenOp>(Op));
    else if (isa<FuncOp>(Op))         return next(Op); // skip functions
    else if (isa<SyntaxOp>(Op))       return Visit(cast<SyntaxOp>(Op));
    else if (isa<PatternOp>(Op))      return Visit(cast<PatternOp>(Op));
    else if (isa<MatchPairOp>(Op))    return Visit(cast<MatchPairOp>(Op));
    else if (isa<MatchTailOp>(Op))    return Visit(cast<MatchTailOp>(Op));
    else if (isa<SubpatternOp>(Op))   return Visit(cast<SubpatternOp>(Op));
    else if (isa<ExpandPacksOp>(Op))  return Visit(cast<ExpandPacksOp>(Op));
    else if (isa<ResolveOp>(Op))      return Visit(cast<ResolveOp>(Op));
    else if (isa<MatchOp>(Op))        return Visit(cast<MatchOp>(Op));
    else if (isa<MatchIdOp>(Op))      return Visit(cast<MatchIdOp>(Op));
    else if (isa<RenameOp>(Op))       return Visit(cast<RenameOp>(Op));
    else if (isa<RenameGlobalOp>(Op)) return Visit(cast<RenameGlobalOp>(Op));
    else if (isa<EnvFrameOp>(Op))     return Visit(cast<EnvFrameOp>(Op));
    else if (isa<ToVectorOp>(Op))     return Visit(cast<ToVectorOp>(Op));
    else if (isa<VectorOp>(Op))       return Visit(cast<VectorOp>(Op));
    else if (isa<LoadModuleOp>(Op))   return Visit(cast<LoadModuleOp>(Op));
    else if (isa<SyntaxClosureOp>(Op))
      return Visit(cast<SyntaxClosureOp>(Op));
    else if (isa<SourceLocOp>(Op))    return Visit(cast<SourceLocOp>(Op));
    else if (UndefinedOp UndefOp = dyn_cast<UndefinedOp>(Op)) {
      setValue(UndefOp, Context.CreateUndefined());
      return next(Op);
    }
    else {
      Op->dump();
      llvm_unreachable("unknown operation");
      return BlockItrTy();
    }
  }

  void LoadArgs(mlir::Block& Body, ValueRefs Args) {
    // This associates values with BlockArguments
    // which later gets assigned to BingingOps (in code)

    auto OpArgs = Body.getArguments();
    assert(OpArgs.size() >= Args.size() + 1
        && "arity should be checked already");
    // OpArg[0] is always the context object
    for (unsigned i = 0; i < Args.size(); ++i) {
      setValue(OpArgs[i + 1], Args[i]);
    }
  }

  BlockItrTy CallFuncOp(heavy::FuncOp F, ValueRefs Args) {
    heavy::Value RestList;
    // check arguments
    unsigned NumArgs = Args.size();
    mlir::FunctionType FT = mlir::cast<mlir::FunctionType>(
        F.getFunctionType());

    // The functions type includes the argument
    // for the context object.
    unsigned NumParams = FT.getNumInputs() - 1;
    // Use NumParamsMax to indicate variadic arguments via ValueRefs.
    // This is supported for continuations only.
    constexpr auto NumParamsMax = std::numeric_limits<decltype(NumParams)>::max();

    if (NumParams == 1 && mlir::isa<HeavyValueRefsTy>(FT.getInputs().back())) {
      NumParams = NumParamsMax;
    } else if (NumParams > 0 && mlir::isa<HeavyRestTy>(FT.getInputs().back())) {
      // Handle a rest param.
      // Check that the number of explicit params
      // are less than the amount of arguments.
      //int NumExplicitArgsMatched = NumParams - 1 - NumArgs;
      if (NumArgs < NumParams - 1) {
        return RaiseError("invalid arity", Value(Undefined()));
      }

      ValueRefs RestArgs = Args.slice(NumParams - 1, NumArgs - (NumParams - 1));
      Args = Args.drop_back(RestArgs.size());
      RestList = Context.CreateList(RestArgs);
    } else {
      // The function type includes the Context as a parameter
      if (NumParams != NumArgs) {
        return RaiseError("invalid arity", Value(Undefined()));
      }
    }

    push_scope();
    mlir::Block& Body = F.getBody().front();
    if (NumParams != NumParamsMax)
      LoadArgs(Body, Args);
    if (RestList)
      setValue(Body.getArguments().back(), RestList);

    BlockItrTy Itr = Body.begin();
    while (Itr != BlockItrTy())
      Itr = Visit(&*Itr);
    pop_scope();

    // The terminator operation should have
    // called Context.Apply() or one of those
    return BlockItrTy();
  }

  // SetContValues
  //  - Loads the values for the results of an Op
  //  - Used by ContOp and ApplyOp (since ApplyOp is dynamic)
  //  - Checks arity
  void SetContValues(mlir::Operation* Op, ValueRefs ContValues) {
    auto Results = Op->getResults();
    assert((Results.empty() ||
           Results.size() == ContValues.size()) &&
        "continuation arity must match");

    for (unsigned i = 0; i < Results.size(); ++i)
      setValue(Results[i], ContValues[i]);
  }

  BlockItrTy Visit(ApplyOp Op) {
    Context.setLoc(getSourceLocation(Op.getLoc()));

    heavy::Value Callee = getValue(Op.getFn());
    ValueRefs Args;
    llvm::SmallVector<heavy::Value, 8> ArgResults;

    auto MArgs = Op.getArgs();  // MLIR Args.
    if (MArgs.size() == 1 &&
        isa<HeavyValueRefsTy>(MArgs.front().getType())) {
      // Just pass all of the continuation args.
      Args = Context.getCallArgs();
    } else {
      ArgResults.resize(MArgs.size());
      for (unsigned i = 0; i < MArgs.size(); ++i)
        ArgResults[i] = getValue(MArgs[i]);
      Args = ValueRefs(ArgResults);
    }

    Context.Apply(Callee, Args);
    return BlockItrTy();
  }

  BlockItrTy Visit(BindingOp Op) {
    // create a Binding
    heavy::Value V = Op.getInput() ? getValue(Op.getInput()) :
                                  heavy::Undefined();
    heavy::Binding* B = Context.CreateBinding(V);
    setValue(Op.getResult(), B);
    return next(Op);
  }

  BlockItrTy Visit(ConsOp Op) {
    // TODO Use PairWithSource to retain source location information.
    heavy::Value A = getValue(Op.getA());
    heavy::Value B = getValue(Op.getB());
    heavy::Pair* V = Context.CreatePair(A, B);
    setValue(Op.getResult(), V);
    return next(Op);
  }

  BlockItrTy Visit(ContOp Op) {
    auto ContArgs = Op.getArgs();
    llvm::SmallVector<heavy::Value, 1> ContValues(ContArgs.size(),
                                                  nullptr);
    for (unsigned i = 0; i < ContArgs.size(); ++i)
      ContValues[i] = getValue(ContArgs[i]);


    Context.Cont(ContValues);
    return BlockItrTy();
  }

  BlockItrTy Visit(IfContOp Op) {
    Value Input = getValue(Op.getInput());
    return Input.isTrue() ? Op.getThenRegion().front().begin() :
                            Op.getElseRegion().front().begin();
  }

  heavy::FuncOp lookupFunction(llvm::StringRef MangledName) {
    // Look up the function in the module where it is defined.
    // This walks the IR linearly.
    // Look only at modules within the Context ModuleOp.
    // (The IR refers to an extern global definition of the variable.
    //  ie not the function itself.)
    auto TopModuleOp = cast<mlir::ModuleOp>(Context.ModuleOp);
    llvm::StringRef ModuleName = Mangler::parseModulePrefix(MangledName);
    auto M = dyn_cast_or_null<mlir::ModuleOp>(
        TopModuleOp.lookupSymbol(ModuleName));
    heavy::FuncOp F;
    if (M)
      F = dyn_cast_or_null<heavy::FuncOp>(M.lookupSymbol(MangledName));
    if (!F) {
      String* ErrMsg = Context.CreateString(
          "undefined reference to function ", MangledName);
      SetError(heavy::SourceLocation(), ErrMsg, Undefined());
      return {};
    }
    return F;
  }

  auto createClosure(mlir::Operation* Op,
                     heavy::FuncOp FuncOp) {
    return [FuncOp](heavy::Context& C, ValueRefs Args) {
      C.OpEval->CallFuncOp(FuncOp, Args);
      return heavy::Undefined();
    };
  }

  auto createClosure(mlir::Operation* Op,
                     heavy::FuncOp FuncOp,
                     mlir::ValueRange CaptureVals,
                     llvm::SmallVectorImpl<heavy::Value>& Captures) {
    for (mlir::Value Val : CaptureVals) {
      Captures.push_back(getBindingOrValue(Val));
    }

    return createClosure(Op, FuncOp);
  }

  BlockItrTy Visit(LambdaOp Op) {
    llvm::SmallVector<heavy::Value, 8> Captures;
    heavy::FuncOp F = lookupFunction(Op.getName());
    if (!F) return {};
    auto CallFn = createClosure(Op, F, Op.getCaptures(), Captures);
    Lambda* L = Context.CreateLambda(CallFn, Captures);

    setValue(Op.getResult(), L);
    return next(Op);
  }

  BlockItrTy Visit(PushContOp Op) {
    llvm::SmallVector<heavy::Value, 8> Captures;
    heavy::FuncOp F = lookupFunction(Op.getName());
    if (!F) return {};
    auto CallFn = createClosure(Op, F, Op.getCaptures(), Captures);
    Context.PushCont(CallFn, Captures);

    return next(Op);
  }

  BlockItrTy Visit(SyntaxOp Op) {
    heavy::FuncOp F = lookupFunction(Op.getName());
    if (!F) return {};
    auto CallFn = createClosure(Op, F);
    Syntax* S = Context.CreateSyntax(CallFn);

    setValue(Op.getResult(), S);
    return next(Op);
  }

  BlockItrTy Visit(PatternOp Op) {
    return Op.getRegion().front().begin();
  }

  BlockItrTy Visit(LiteralOp Op) {
    // Map the IR value node to the run-time value
    heavy::Value V = Op.getInput().getValue(Context);
    setValue(Op.getResult(), V);
    return next(Op);
  }

  BlockItrTy Visit(LoadRefOp Op) {
    // Load from a ValueRefs object which is accessible
    // through the Context object.
    uint32_t Index = Op.getIndex();

    mlir::Type RefsType = Op.getValueRefs().getType();
    heavy::ValueRefs ValueRefs;

    if (isa<HeavyContextTy>(RefsType)) {
      // Assume we always use the current context object.
      auto* Callee = cast<Lambda>(Context.getCallee());
      ValueRefs = Callee->getCaptures();
    } else if (isa<HeavyValueRefsTy>(RefsType)) {
      ValueRefs = Context.getCallArgs();
    }

    // This is defensive for captures if the IR is ill-formed,
    // but bad continuation arity is a run-time error.
    if (Index >= ValueRefs.size()) {
      heavy::SourceLocation Loc = getSourceLocation(Op.getLoc());
      return SetError(Loc, "invalid arity for continuation");
    }

    heavy::Value Result = ValueRefs[Index];

    setValue(Op.getResult(), Result);
    return next(Op);
  }

  BlockItrTy Visit(LoadModuleOp Op) {
    heavy::Symbol* ModuleName = Context.CreateSymbol(Op.getName());
    Context.PushCont([](heavy::Context& C, ValueRefs) {
      heavy::Symbol* ModuleName = cast<Symbol>(C.getCapture(0));
      C.PushCont([](heavy::Context& C, ValueRefs) {
        heavy::Symbol* ModuleName = cast<Symbol>(C.getCapture(0));
        C.InitModule(ModuleName);
      }, CaptureList{ModuleName});
      C.LoadModule(ModuleName);
    }, CaptureList{ModuleName});
    Context.Cont();
    return BlockItrTy();
  }

  BlockItrTy Visit(LoadGlobalOp Op) {
    Value Val = Context.GetKnownValue(Op.getName());
    if (!Val) {
      Val = Undefined();
    }
    setValue(Op, Val);
    return next(Op);
  }

  BlockItrTy Visit(GlobalOp Op) {
    // Skip external global ops.
    if (Op.isExternal())
      return BlockItrTy();

    Context.PushCont([Op](heavy::Context& C, ValueRefs Args) mutable {
      assert(Args.size() == 1 && "invalid continuation arity");
      heavy::Value Result = Args[0];
      // Mutable globals must be wrapped with a binding
      if (!isa<Syntax>(Result))
        Result = C.CreateBinding(Args[0]);
      C.AddKnownAddress(Op.getSymName(), Result);
      C.Cont(Undefined());
    }, ValueRefs());

    push_scope();
    BlockItrTy Itr = Op.getInitializer().front().begin();
    while (Itr != BlockItrTy())
      Itr = Visit(&*Itr);
    pop_scope();
    return BlockItrTy();
  }

  BlockItrTy Visit(CommandOp Op) {
    push_scope();
    BlockItrTy Itr = Op.getBody().front().begin();
    while (Itr != BlockItrTy())
      Itr = Visit(&*Itr);
    pop_scope();
    return BlockItrTy();
  }

  BlockItrTy Visit(SetOp Op) {
    heavy::Binding* B = cast<heavy::Binding>(getBindingOrValue(Op.getBinding()));
    heavy::Value RHS = getValue(Op.getInput());
    B->setValue(RHS);
    return next(Op);
  }

  BlockItrTy Visit(ToVectorOp Op) {
    heavy::SourceLocation Loc = getSourceLocation(Op.getLoc());
    heavy::Value Input = getValue(Op.getInput());
    heavy::Vector* Vector = nullptr;

    if (isa<Empty>(Input)) {
      Vector = Context.CreateVector({});
    } else {
      if(!isa<Pair>(Input))
        return SetError(Loc, "should be a non-empty list", Input);

      llvm::SmallVector<heavy::Value, 8> Xs;
      heavy::Value Next = Input;
      while (heavy::Pair* P = dyn_cast<Pair>(Next)) {
        Xs.push_back(P->Car);
        Next = P->Cdr;
      }
      if (!isa<Empty>(Next))
        return SetError(Loc, "should be a proper list", Next);

      Vector = Context.CreateVector(Xs);
    }
    setValue(Op, Vector);
    return next(Op);
  }

  BlockItrTy Visit(VectorOp Op) {
    unsigned Size = Op.getArgs().size();
    heavy::Vector* Vector = Context.CreateVector(Size);
    auto Vals = Op.getArgs();
    for (unsigned I = 0; I < Size; ++I)
      Vector->get(I) = getValue(Vals[I]);

    setValue(Op, Vector);
    return next(Op);
  }

  BlockItrTy Visit(EnvFrameOp Op) {
    unsigned Size = Op.getArgs().size();
    heavy::EnvFrame* EnvFrame = Context.CreateEnvFrame(Size);
    llvm::MutableArrayRef<Binding*> Bindings = EnvFrame->getBindings();
    auto Vals = Op.getArgs();
    for (unsigned I = 0; I < Size; ++I)
      Bindings[I] = cast<Binding>(getBindingOrValue(Vals[I]));

    setValue(Op, EnvFrame);
    return next(Op);
  }

  BlockItrTy Visit(SpliceOp Op) {
    heavy::SourceLocation Loc = getSourceLocation(Op.getLoc());
    heavy::Value LHS = getValue(Op.getA());
    heavy::Value RHS = getValue(Op.getB());

    // LHS must be list.
    if (!isa<heavy::Pair>(LHS) && !isa<heavy::Empty>(LHS)) {
      return SetError(Loc, "splicing operand expected list", LHS);
    }

    // A new list must be created
    // Dummy is the start point that is not part of the result
    // as it is not on the heap
    heavy::Pair Dummy = heavy::Pair(nullptr, nullptr);
    heavy::Pair* Dest = &Dummy;
    heavy::Value Temp = LHS;

    while (Pair* Cur = dyn_cast<heavy::Pair>(Temp)) {
      heavy::Pair* New = Context.CreatePair(Cur->Car);
      Dest->Cdr = New;
      Dest = New;
      Temp = Cur->Cdr;
    }
    Temp = RHS;
    while (Pair* Cur = dyn_cast<heavy::Pair>(Temp)) {
      heavy::Pair* New = Context.CreatePair(Cur->Car);
      Dest->Cdr = New;
      Dest = New;
      Temp = Cur->Cdr;
    }
    heavy::Value Result = Dummy.Cdr ? Dummy.Cdr : Empty{};
    setValue(Op, Result);
    return next(Op);
  }

  // A pattern failing to match results in going to the next pattern
  // or, in the case of a pack, it begins matching the rest of the list.
  BlockItrTy patternFail(mlir::Operation* Op) {
    // We should currently be in the scope of a PatternOp or SubpatternOp
    assert((isa<MatchOp, MatchPairOp, MatchTailOp,
                SubpatternOp, MatchIdOp>(Op)) &&
        "Operation must be a pattern matcher");

    mlir::Operation* PatternOp = Op->getParentOp();

    if (auto SubpatternOp = dyn_cast<heavy::SubpatternOp>(PatternOp))
      return BlockItrTy();

    assert(isa<heavy::PatternOp>(PatternOp) &&
        "expecting a PatternOp.");

    // Abort the current pattern's scope and move to the next operation.
    return next(Op);
  }

  BlockItrTy Visit(MatchOp Op) {
    heavy::Value P = Op.getVal().getValue(Context);
    heavy::Value E = getValue(Op.getInput());
    if (Symbol* S = dyn_cast<Symbol>(E)) {
      // If the symbol is in the environment we can skip
      // because it will not match a literal.
      EnvEntry Entry = Context.Lookup(S);
      if (Entry)
        return patternFail(Op);
    }
    if (equal(P, E)) {
      return next(Op);
    }
    return patternFail(Op);
  }

  BlockItrTy Visit(MatchPairOp Op) {
    heavy::Value E = getValue(Op.getInput());
    if (auto* Pair = dyn_cast<heavy::Pair>(E)) {
      Context.setLoc(E.getSourceLocation());
      setValue(Op.getCar(), Pair->Car);
      setValue(Op.getCdr(), Pair->Cdr);
      return next(Op);
    }
    return patternFail(Op);
  }

  BlockItrTy Visit(MatchTailOp Op) {
    // Here we include the last cdr in the length
    // of a list proper or improper.
    heavy::Value E = getValue(Op.getInput());
    uint32_t TargetLen = Op.getLength();
    assert(TargetLen >= 1 && "expecting positive length");
    uint32_t TotalLen = 1;
    heavy::Value Cur = E;
    while (auto* Pair = dyn_cast<heavy::Pair>(Cur)) {
      ++TotalLen;
      Cur = Pair->Cdr;
    }
    if (TotalLen < TargetLen)
      return patternFail(Op);
    Cur = E;
    for (uint32_t i = 0; i < TotalLen - TargetLen; i++)
      Cur = cast<heavy::Pair>(Cur)->Cdr;
    setValue(Op.getTail(), Cur);
    return next(Op);
  }

  BlockItrTy Visit(ExpandPacksOp Op) {
    heavy::SourceLocation Loc = getSourceLocation(Op.getLoc());
    setValue(Op.getResult(), getValue(Op.getCdr()));
    llvm::SmallVector<heavy::Value, 4> Packs(Op.getPacks().size());
    mlir::ValueRange PackInputs = Op.getPacks();
    auto BlockArgs = Op.getBody().getArguments();
    assert(Packs.size() >= 1 && "should have some packs");
    for (unsigned i = 0; i < Packs.size(); i++)
      Packs[i] = getValue(PackInputs[i]);

    // Recall that each pack is a list in reverse order.
    while (isa<heavy::Pair>(Packs.front())) {
      // Set each block argument to the cdr of each pack.
      push_scope();
      for (unsigned i = 0; i < Packs.size(); i++) {
        auto* Pair = dyn_cast<heavy::Pair>(Packs[i]);
        if (!Pair)
          return SetError(Loc, "expansion packs should have equal length");
        setValue(BlockArgs[i], Pair->Car);
        Packs[i] = Pair->Cdr;
      }
      BlockItrTy Itr = Op.getBody().front().begin();
      while (Itr != BlockItrTy())
        Itr = Visit(&*Itr);
      // ResolveOp calls pop_scope.
    }

    for (unsigned i = 0; i < Packs.size(); i++) {
      if (!isa<Empty>(Packs[i]))
        return SetError(Loc, "expansion packs should have equal length");
    }

    return next(Op);
  }

  BlockItrTy Visit(SubpatternOp Op) {
    heavy::Value E = getValue(Op.getInput());
    heavy::Pair* Tail = dyn_cast<heavy::Pair>(getValue(Op.getTail()));

    // Match the empty list.
    if (isa<heavy::Empty>(E)) {
      for (mlir::Value Pack : Op.getPacks())
        setValue(Pack, Empty());
      return next(Op);
    }

    // Initialize result packs for storage as reverse ordered lists.
    for (mlir::Value PackResult : Op.getPacks())
      setValue(PackResult, Empty());

    assert(Op.getBody().getNumArguments() == 1
        && "body should have single argument");
    mlir::Value BodyArg = Op.getBody().getArgument(0);
    // Visit the subpattern body for each element in E
    // stopping when we find tail or a non-pair object.
    // Each "pack" should be a list.
    while (auto* Pair = dyn_cast<heavy::Pair>(E)) {
      if (Pair == Tail)
        break;
      push_scope();
      BlockItrTy Itr = Op.getBody().front().begin();
      setValue(BodyArg, Pair->Car);
      while (Itr != BlockItrTy())
        Itr = Visit(&*Itr);
      E = Pair->Cdr;
      // ResolveOp calls pop_scope.
    }

    return next(Op);
  }

  BlockItrTy Visit(ResolveOp Op) {
    if (auto ParentOp = dyn_cast<SubpatternOp>(Op->getParentOp())) {
      // We are at the terminator of a subpattern body region.
      assert(ParentOp.getPacks().size() ==
             Op.getArgs().size() &&
             "expecting value ranges of equal size");
      // Store packs on the stack until we can pop the scope.
      llvm::SmallVector<heavy::Value, 4> Packs(
          ParentOp.getPacks().size(), nullptr);
      mlir::ValueRange ResolveArgs = Op.getArgs();
      mlir::ResultRange MResults = ParentOp.getPacks();
      // Construct each pack as a reversed ordered list.
      for (unsigned i = 0; i < Packs.size(); i++)
        Packs[i] = Context.CreatePair(getValue(ResolveArgs[i]),
                                      getValue(MResults[i]));

      // Set the results in the parent scope.
      pop_scope();
      for (unsigned i = 0; i < Packs.size(); i++)
        setValue(MResults[i], Packs[i]);

      return BlockItrTy();
    }

    auto ExpandPacksOp = cast<heavy::ExpandPacksOp>(Op->getParentOp());
    assert(Op.getArgs().size() == 1 && "expecting single result");
    heavy::Value CurrentResult = getValue(Op.getArgs().front());
    heavy::Value Result = Context.CreatePair(CurrentResult,
                                      getValue(ExpandPacksOp.getResult()));

    // Set the result in the parent scope.
    pop_scope();
    setValue(ExpandPacksOp.getResult(), Result);

    return BlockItrTy();
  }

  BlockItrTy Visit(MatchIdOp Op) {
    heavy::Value P = getValue(Op.getVal());
    heavy::Value E = getValue(Op.getInput());
    if (P == E) {
      return next(Op);
    }
    return patternFail(Op);
  }

  BlockItrTy Visit(SyntaxClosureOp Op) {
    // Create a SyntaxClosure with the provided env argument.
    heavy::Value Input = getValue(Op.getInput());
    heavy::Value Env = getValue(Op.getEnv());
    SyntaxClosure* SC = Context.CreateSyntaxClosure(Context.getLoc(),
                                                    Input, Env);
    setValue(Op.getResult(), SC);

    return next(Op);
  }

  BlockItrTy Visit(RenameOp Op) {
    heavy::Value Capture = getValue(Op.getCapture());
    heavy::Symbol* Id = Context.CreateSymbol(Op.getId());
    heavy::Binding* B = Context.CreateBinding(Id, Capture);
    setValue(Op.getResult(), B);

    return next(Op);
  }

  BlockItrTy Visit(RenameGlobalOp Op) {
    heavy::SourceLocation Loc = Context.getLoc();
    heavy::Value ExtName = Context.CreateExternName(Loc, Op.getSym());
    heavy::Symbol* Id = Context.CreateSymbol(Op.getId());
    heavy::Binding* B = Context.CreateBinding(Id, ExtName);
    setValue(Op.getResult(), B);

    return next(Op);
  }

  BlockItrTy Visit(OpGenOp Op) {
    heavy::OpGen* OpGen = Context.OpGen;  // For debug only.
    heavy::Value PrevEnv = Context.getEnvironment();
    heavy::Value Input = getValue(Op.getInput());
    heavy::Value Env = getValue(Op.getEnv());
    Context.setEnvironment(Env);
    mlir::Value Result = Context.OpGen->Visit(Input);
    Context.setEnvironment(PrevEnv);
    heavy::Value Output = heavy::OpGen::fromValue(Result);
    assert(OpGen == Context.OpGen && "OpGen visit should not unwind itself");
    if (!Context.OpGen || !Context.OpGen->CheckError())
      Context.Cont(Output);
    return BlockItrTy();
  }

  BlockItrTy Visit(SourceLocOp Op) {
    heavy::SourceLocation Loc = getSourceLocation(Op.getLoc());
    heavy::Value V = Context.CreateSourceValue(Loc);
    setValue(Op.getResult(), V);
    return next(Op);
  }
};

namespace base {
void op_eval(Context& C, ValueRefs Args) {
  if (Args.size() != 1) {
    return C.RaiseError("invalid arity");
  }
  mlir::Operation* Op = dyn_cast<mlir::Operation>(Args[0]);
  if (!Op) {
    return C.RaiseError("expecting operation");
  }

  // TODO Make the module own the OpEval instance. (maybe?)
  if (!C.OpEval) {
    C.OpEval = new OpEvalImpl(C);
    C.PushModuleCleanup(HEAVY_BASE_LIB_STR,
      C.CreateLambda([](Context& C, ValueRefs) {
        llvm_unreachable("FIXME find out why we do not get here");
        assert(C.OpEval && "OpEval should be set.");
        // Cleanup the OpEval object.
        delete C.OpEval;
      }, CaptureList{}));
  }

  C.OpEval->Eval(Op);
}
}

}
