(import (heavy base))
(define-library (my lib)
  (import (heavy base))
  (import (heavy mlir))
  (begin
    (define (hello-module x)
      (write "hello module!")
      (newline)
      (write x)
      (newline)
      )
    (define-syntax hello-module-syntax
      (syntax-rules ()
        ((hello-module-syntax x)
          (begin
            (write "syntax: ")
            (hello-module x))
          )))
    (write "end of init")
    (newline))
  (export hello-module
          hello-module-syntax)
)
(write "end of module")
(newline)
