(import (heavy base))
(define-library (my lib)
  (import (heavy base))
  (begin
    (define (hello-module x)
      (write "hello module!")
      (newline)
      (write x))
    (write "end of init")
    (newline))
  (export hello-module)
)
(write "end of module")
(newline)
